#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-tt2trk

set -e  

tt=$(jq -r .tt config.json)

# create symbolic link here
tt_base_name=${tt##*/}
rm -f ${tt_base_name}
ln -s ${tt} ${tt_base_name}


time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=exp --source=${tt_base_name} --output=${tt_base_name}.trk.gz

# move file to trk folder
mkdir -p track
mv ${tt_base_name}.trk.gz track/trk.gz
