#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-tt2trk

set -e  

tt=$(jq -r .tt config.json)


time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=exp --source=${tt} --output=data.${tt##*/}.trk.gz

# move file to trk folder
mkdir -p track
mv data.${tt##*/}.trk.gz track/trk.gz
